apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-test
  namespace: storage-csi
spec:
  selector:
    matchLabels:
      app: csi-test
  template:
    metadata:
      labels:
        app: csi-test
    spec:
      containers:
        - name: csi-test
          image: docker.io/alpine:latest
          command: ["sleep", "infinite"]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "64Mi"
              cpu: "0"
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: csi
              mountPath: csi
      volumes:
        - name: csi
          persistentVolumeClaim:
            claimName: test-pvc
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
