# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: storage-csi
  labels:
    app: test-pvc
spec:
  storageClassName: blackmesa-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
