apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.infra.d464.sh
  labels:
    app.kubernetes.io/instance: csi.infra.d464.sh
    app.kubernetes.io/part-of: storage-csi
    app.kubernetes.io/name: csi.infra.d464.sh
    app.kubernetes.io/component: storage-csi-driver
spec:
  # Supports persistent and ephemeral inline volumes.
  volumeLifecycleModes:
  - Persistent
    # - Ephemeral
  # To determine at runtime which mode a volume uses, pod info and its
  # "csi.storage.k8s.io/ephemeral" entry are needed.
  podInfoOnMount: true
  # Kubernetes may use fsGroup to change permissions and ownership 
  # of the volume to match user requested fsGroup in the pod's SecurityPolicy
  fsGroupPolicy: File
