apiVersion: v1
kind: Secret
metadata:
  name: storage-csi
stringData:
  STORAGE_HOST: ""
  STORAGE_SSH_PORT: "22"
  STORAGE_SSH_USER: ""
  STORAGE_SSH_KEY: ""
  STORAGE_SSH_SUDO: "true"
  STORAGE_ZFS_DATASET: ""
